### ISSUE TITLE
Publish Type Definitions

### ISSUE THREAD

**Issue by bfsmith** [jcuenod/ReferenceParser#12]
The Typescript type definitions aren't published with the package, making the package not friendly to Typescript projects importing it.

It's also packaging way more than necessary in the package (docs, src, tests). It could be parred down to just the package.json and lib.

**Comment by jcuenod** [comment]
Thanks! I'll look into fixing this...

**Comment by jcuenod** [comment]
f9b2bc1999deb69d7c4b7351871f68327c1769a7 and 3955e4aa626836e9389b8cd4cc01a8b0776fdc9c
